server:
  port: 7776
mybatis:
  typeAliasesPackage: com.sqber.personMgr.entity
  mapperLocations: classpath*:/mapping/*.xml
spring:
  jackson:
   date-format: yyyy-MM-dd HH:mm:ss
   time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 1000Mb
  thymeleaf:
    cache : false
  cache:
    type: SIMPLE
  datasource:
    mysql:
      #JdbcUrl: jdbc:mysql://127.0.0.1:3306/personMgr?useSSL=false&serverTimezone=UTC #开发
      JdbcUrl: jdbc:mysql://127.0.0.1:3306/personMgr?useSSL=false&serverTimezone=Asia/Shanghai #开发
      DriverClassName: com.mysql.cj.jdbc.Driver
      Username: root
      Password: 123456
      useSSL: false
      type: com.zaxxer.hikari.HikariDataSource
      minIdle: 5
      maxPoolSize: 15
      isAutoCommit: true
      idleTimeout: 30000
      maxLifetime: 1800000
      connectionTimeout: 30000
      connectionTestQuery: SELECT 1
logging:
    level:
      com:
        sqber:
          personMgr:
                  dal: debug
fileupload:
  savePath: c:/personMgr/upload/

justauth:
  enabled: true
  type:
    QQ:
      client-id: 1015***52
      client-secret: 7ded389d52b****675f291f3489afb
      redirect-uri: http://39.107.227.57:8006/personMgr/oauth/qq/callback
      union-id: false
    GITHUB:
      client-id: Iv1.9535b67931d50085
      client-secret: 63057336b4f8a2eddbda1b95f82d4eb8a396a66d
      redirect-uri: http://39.107.227.57:8006/personMgr/oauth/github/callback
    WECHAT_OPEN:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat_open/callback
    WECHAT_MP:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat_mp/callback
    WECHAT_ENTERPRISE:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat_enterprise/callback
      agent-id: 1000002
  cache:
    type: default
